FROM ghcr.io/zhayujie/chatgpt-on-wechat:latest

ARG OPEN_AI_API_KEY
ARG OPEN_AI_PROXY
ARG SINGLE_CHAT_PREFIX
ARG SINGLE_CHAT_REPLY_PREFIX
ARG GROUP_CHAT_PREFIX
ARG GROUP_NAME_WHITE_LIST
ARG IMAGE_CREATE_PREFIX
ARG CONVERSATION_MAX_TOKENS
ARG SPEECH_RECOGNITION
ARG CHARACTER_DESC
ARG EXPIRES_IN_SECONDS
ARG TIME_GAP
ARG KEEPLIVE_ID

ENTRYPOINT ["/entrypoint.sh"]